services:
  db:
    image: postgis/postgis:16-3.4
    container_name: grafomov_db
    environment:
      POSTGRES_DB: grafomov
      POSTGRES_USER: grafomov
      POSTGRES_PASSWORD: grafomov_2026
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
